
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio
  namespace: portfolio-portfolio
spec:
  selector:
    app: portfolio
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-web
      name: portfolio
    