apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solgames-pipeline
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/solgames-fun/solgames-pipeline.git
    targetRevision: HEAD
    path: game2
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true