
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio2
  name: portfolio2
  namespace: portfolio-portfolio2
spec:
  selector:
    matchLabels:
      app: portfolio2
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio2
    spec:
      containers:
      - name: portfolio2
        image: dockerghosh/portfolio:latest
        ports:
        - containerPort: 3001
          name: http-web
    